apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "discord-orel-bot.fullname" . }}-cm
  labels:
    name: {{ include "discord-orel-bot.name" . }}
    instance: {{ .Release.Name }}
data:
  config.yaml: |
{{ tpl (.Files.Get "configs/config.yaml") . | indent 4 }}
