apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discord-orel-bot.fullname" . }}-token
  labels:
    name: {{ include "discord-orel-bot.name" . }}
    instance: {{ .Release.Name }}
data:
  DISCORD_TOKEN: {{ .Values.secret.token | required "A discord token is required "}}
type: Opaque