apiVersion: v1
kind: ConfigMap
metadata:
  name: discord-orel-bot-cm
  labels:
    app: discord-orel-bot-cm
data:
  config.yaml: |
    en:
      curses:
        - shut up
      answers:
        - Lame.
    he:
      curses:
        - שתוק
      answers:
        - תשמע, אתה גרוע
